const express=require("express"),DB=require("better-sqlite3"),path=require("path");
const app=express(),db=new DB(path.join(__dirname,"data.sqlite"));
const PORT=process.env.PORT||3000,KEY=process.env.ADMIN_KEY||"change-this-key";
db.exec(`CREATE TABLE IF NOT EXISTS reviews(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,rating INTEGER,pet TEXT,review TEXT,approved INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS bookings(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,phone TEXT,pet TEXT,service TEXT,date TEXT,time TEXT,address TEXT,lat REAL,lng REAL,notes TEXT,status TEXT DEFAULT 'new',created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
app.use(express.json({limit:"1mb"}));app.use(express.static(path.join(__dirname,"public")));
const admin=(req,res,next)=>{if((req.headers["x-admin-key"]||"")!==KEY)return res.status(401).json({error:"Unauthorized"});next()};
app.get("/api/reviews",(q,s)=>s.json({reviews:db.prepare("SELECT * FROM reviews WHERE approved=1 ORDER BY id DESC").all(),stats:db.prepare("SELECT COUNT(*) count,COALESCE(AVG(rating),0) avg FROM reviews WHERE approved=1").get()}));
app.post("/api/reviews",(q,s)=>{let{x,rating,pet,review}=q.body;let name=x||q.body.name,r=Number(rating);if(!name||!review||r<1||r>5)return s.status(400).json({error:"Name, rating and review are required"});let z=db.prepare("INSERT INTO reviews(name,rating,pet,review) VALUES(?,?,?,?)").run(String(name).slice(0,80),r,String(pet||"").slice(0,30),String(review).slice(0,1500));s.status(201).json({ok:true,id:z.lastInsertRowid})});
app.post("/api/bookings",(q,s)=>{let b=q.body;if(!b.name||!b.phone||!b.pet||!b.service||!b.date||!b.time)return s.status(400).json({error:"Complete required fields"});let z=db.prepare("INSERT INTO bookings(name,phone,pet,service,date,time,address,lat,lng,notes) VALUES(?,?,?,?,?,?,?,?,?,?)").run(b.name,b.phone,b.pet,b.service,b.date,b.time,b.address||"",b.lat||null,b.lng||null,b.notes||"");s.status(201).json({ok:true,id:z.lastInsertRowid})});
app.get("/api/admin/reviews",admin,(q,s)=>s.json(db.prepare("SELECT * FROM reviews ORDER BY id DESC").all()));
app.patch("/api/admin/reviews/:id",admin,(q,s)=>{db.prepare("UPDATE reviews SET approved=? WHERE id=?").run(q.body.approved?1:0,q.params.id);s.json({ok:true})});
app.delete("/api/admin/reviews/:id",admin,(q,s)=>{db.prepare("DELETE FROM reviews WHERE id=?").run(q.params.id);s.json({ok:true})});
app.get("/api/admin/bookings",admin,(q,s)=>s.json(db.prepare("SELECT * FROM bookings ORDER BY id DESC").all()));
app.patch("/api/admin/bookings/:id",admin,(q,s)=>{db.prepare("UPDATE bookings SET status=? WHERE id=?").run(q.body.status,q.params.id);s.json({ok:true})});
app.listen(PORT,()=>console.log("HVS running on port "+PORT));